// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shiko.LessonExerciseProvider.Api.Data;

#nullable disable

namespace Shiko.LessonExerciseProvider.Api.Data.Migrations
{
    [DbContext(typeof(LessonExerciseDbContext))]
    [Migration("20260530121554_AddSoftDeleteToLessonExercises")]
    partial class AddSoftDeleteToLessonExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shiko.LessonExerciseProvider.Api.Models.LessonExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "OrderIndex");

                    b.ToTable("LessonExercises", "lesson_exercise");
                });

            modelBuilder.Entity("Shiko.LessonExerciseProvider.Api.Models.UserCompletedLesson", b =>
                {
                    b.Property<Guid>("UserCourseProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserCourseProgressId", "LessonExerciseId");

                    b.HasIndex("LessonExerciseId");

                    b.ToTable("UserCompletedLessons", "lesson_exercise");
                });

            modelBuilder.Entity("Shiko.LessonExerciseProvider.Api.Models.UserCourseProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("UserCourseProgresses", "lesson_exercise");
                });

            modelBuilder.Entity("Shiko.LessonExerciseProvider.Api.Models.UserCompletedLesson", b =>
                {
                    b.HasOne("Shiko.LessonExerciseProvider.Api.Models.LessonExercise", "LessonExercise")
                        .WithMany()
                        .HasForeignKey("LessonExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shiko.LessonExerciseProvider.Api.Models.UserCourseProgress", "UserCourseProgress")
                        .WithMany("CompletedLessons")
                        .HasForeignKey("UserCourseProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonExercise");

                    b.Navigation("UserCourseProgress");
                });

            modelBuilder.Entity("Shiko.LessonExerciseProvider.Api.Models.UserCourseProgress", b =>
                {
                    b.Navigation("CompletedLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
